### ISSUE TITLE
Separate boards

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/Mini17#31]
Put all interface (microphone, speaker, keyboard, PTT/F1/F2 buttons, rotary encoder, Kenwood connector, OLED display) on a separate board.

**Comment by JKI757** [comment]
Interesting way of looking at it I guess -- was looking at the TYT design, they've got the microphone, keypad, and display on a separate board, but all the other interface components are on the mainboard.  

I think we need someone to create a physical design of some sort, because that is going to drive these kinds of discussions.  I was even thinking as I worked on the board tonight, why not just use the tyt front panel as it is?   essentially we'd just be replacing the mainboard, we could even re-use the volume, encoder (which I'm still not finding one that I think will work), PTT buttons, etc.

**Comment by LongHairedHacker** [comment]
I don't think creating a replacement mainboard for another device is the best approach here.
It sure is tempting idea you get an enclosure, a battery, display and everything in nice form factor (also chargers and other accessories...)
However I already had some trouble getting a MD380 to mod for M17 for a reasonable price.
So it might not be the best idea to tie peoples ability to build a mini17 to the availability of some existing radio.
Also that doesn't really feel open hardware to me.

In my opinion it might be a little to early to think about physical design.
I'd much rather prefer to to have two stacked rectangular boards in the first iteration.
It shouldn't be to hard to come up with an enclosure for something like that using a lasercutter or a 3d printer.

Once the design verified to work, we can talk designing a nice polished enclosure and make the boards fit in that.

**Comment by JKI757** [comment]
You absolutely have to have some physical design to line up your board design to, otherwise you are building a dev board, you might as well totally ignore form factor, and you need to plan to completely redesign it when you decide you want to build a handheld radio -- and there's no point in doing any board at all if you're going to do that, you just buy the manufacturer supplied dev board (https://www.ti.com/tool/CC1200DK) and focus your development efforts on the software. 

We've decided to go a different way with this, but MD380s are 130 bucks on Amazon in apparently unlimited quantity, and they're even cheaper used on eBay.  I still think that simply designing a drop-in main board replacement for that radio (or the 390 or any other radio already in the supply chain) would be far superior to other approaches for all the reasons you list above.

**Comment by sp5wwp** [comment]
The design is now split into 2.
